fix: authorization state enum
SwitchEV/iso15118 pull request #52
Opened 2022-05-26 11:01 UTC by danielgordon-switch-ev

This PR replaces the true/false return value for `is_authorized` with Accepted/Rejected/Ongoing, since an AuthorizationReq can be retried to deal with the time limit imposed by ISO 15118-2.

This also adds some unit tests and replaces a repeatedly-used test value with a constant.

2022-05-27 09:15 UTC, shalinnijel2 requested changes
Just a couple of minor changes - else LGTM.

2022-05-27 10:11 UTC, danielgordon-switch-ev commented on tests/secc/states/test_iso15118_2_states.py
> +            (AuthorizationStatus.REJECTED, Authorization),
I think the best way would be to make a test marked with `xfail` -- this documents what the correct behavior is, as well as that we know it's not implemented yet, while still allowing the test suite to pass.

We can add a ticket to add the functionality needed to make that test pass and link that to the TODO.

2022-05-27 10:12 UTC, danielgordon-switch-ev commented on iso15118/secc/states/iso15118_2_states.py
Yes, will do.

2022-05-27 10:12 UTC, danielgordon-switch-ev commented on iso15118/secc/controller/interface.py
> +    def is_authorized(self) -> bool:
Good catch, will fix.

2022-05-27 15:26 UTC, danielgordon-switch-ev commented on tests/secc/states/test_iso15118_2_states.py
> +            (AuthorizationStatus.REJECTED, Authorization),
https://github.com/SwitchEV/iso15118/issues/54

2022-05-30 15:19 UTC, tropxy requested changes

2022-05-31 14:29 UTC, danielgordon-switch-ev commented on iso15118/secc/states/iso15118_20_states.py
>              auth_status = Processing.FINISHED
I added a reference below to a placeholder ticket (need to fill this in with more info) for doing this in 15118-20: https://github.com/SwitchEV/iso15118/issues/56

As this isn't directly relevant to the task this PR is for, and no functionality is lost (the REJECTED case didn't work before either), it's probably better to deal with this later, unless it's really just this one line.

2022-06-01 12:25 UTC, shalinnijel2 approved these changes

2022-06-01 13:41 UTC, tropxy approved these changes

2022-06-01 13:43 UTC, merged